languages: java

jdk:
- oraclejdk8

branches:
  only:
  - master

addons:
  sonarcloud:
    organization: "google-cloud-spanner-hibernate"

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -B -V -q -Dsonar.projectKey=google-cloud-spanner-hibernate
