language: java

jdk:
  - oraclejdk8

dist: trusty

branches:
  only:
  - master
  - test

cache:
  directories:
    - $HOME/.m2

addons:
  sonarcloud:
    organization: "google-cloud-spanner-hibernate"
    token:
      secure: "pNSuPozHIh/W3h/CYTYFb2r3iui2ecE+984LhAL+nuVaarUINRw9kiVzTOUkg0xpeSe9CmoGqSd5z0VsGNk3exDdaPm4+jeJvgluNRNaCQGYd0w0GiSMM1L2EigP78S61hA7EH7SjzAQfieBQxA/py6EOWiDIswdu5myGYp7zKashJOse8fXrkodBufAigxEjhm4eHT2z0IHUguw/UPBCNqNZQiD2ma4xCgK7AXbPcjDYxo9Z43wM5SacGZt0lHfFTjse8fRgWXDdvHIuRTrG4NCN0NpIrVQx8kWHzLkwzG2mSWtyXEzlh6a0wRF37/RZePGXc3yRIJKmoyvfpVdmzkJwgXzVgU6MPFH14Aa7FHa4GpjqPbk/Tx3E/FhyoLPsfXWF+RVq7XmG5+tZ6QabqDhtINFS4kPJrP7Ni6vePfOqg5ZOKQpDlQbnfNK/KasQ/RzyhsQOFc3CzEWJZOQJ2/af3a8AkbKrVsm5MbFCeQ7GSgv22PdAHGuJLuZJ5Qot2fcdlpWs+z++oYtEuvJafIETdBlgtXtbxMee2IsYD7sOvsYCWne4WP4Mfdh+YDNlGjrqLMV/QRjPKfe7Uaz2K7R6vzcoP8J7ou8SjfNtIpyvEkcwtjnYnzmYp+pS7olqprvXp+aqcQNLfi+Xqyuj0cHB8txTfCVHDvCdLw1WRE="

install:
  - ./mvnw clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P disable-integration-tests;

before_install:
  - if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then
      openssl aes-256-cbc -K $encrypted_4f86105f28dd_key -iv $encrypted_4f86105f28dd_iv -in travis.tar.gz.enc -out travis.tar.gz -d;
      tar -xzf travis.tar.gz;
      export GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/admin.json;
      export GOOGLE_CLOUD_PROJECT=cloud-spanner-hibernate-ci;
    fi;

script:
  - if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then
      ./mvnw org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -B -V Dsonar.projectKey=google-cloud-spanner-hibernate -Dhibernate.show_sql=false;
    else
      ./mvnw verify -B -V -P disable-integration-tests;
    fi;

